// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBza7QlAoepTkn8p83eoMY5bJg4LLfE3nE',
    appId: '1:126827222127:web:33ccae73cecb5e3861299a',
    messagingSenderId: '126827222127',
    projectId: 'app-register-login-flutter',
    authDomain: 'app-register-login-flutter.firebaseapp.com',
    storageBucket: 'app-register-login-flutter.firebasestorage.app',
    measurementId: 'G-VJ59TNWL1L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASbCV2A_YstHf076sUxqbgx7x9ouaooSw',
    appId: '1:126827222127:android:a60bdf6f6cc2220f61299a',
    messagingSenderId: '126827222127',
    projectId: 'app-register-login-flutter',
    storageBucket: 'app-register-login-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDESfeOA3RhC3yFnuwtRqKODw5G48LRaIw',
    appId: '1:126827222127:ios:e04393f1727dcddf61299a',
    messagingSenderId: '126827222127',
    projectId: 'app-register-login-flutter',
    storageBucket: 'app-register-login-flutter.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthProviderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDESfeOA3RhC3yFnuwtRqKODw5G48LRaIw',
    appId: '1:126827222127:ios:e04393f1727dcddf61299a',
    messagingSenderId: '126827222127',
    projectId: 'app-register-login-flutter',
    storageBucket: 'app-register-login-flutter.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthProviderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBza7QlAoepTkn8p83eoMY5bJg4LLfE3nE',
    appId: '1:126827222127:web:9329178b1b212d1261299a',
    messagingSenderId: '126827222127',
    projectId: 'app-register-login-flutter',
    authDomain: 'app-register-login-flutter.firebaseapp.com',
    storageBucket: 'app-register-login-flutter.firebasestorage.app',
    measurementId: 'G-HG9RBMPFGF',
  );
}
